### ISSUE TITLE
Add vcpkg port

### ISSUE THREAD

**Issue by sdcb** [Microsoft/DXUT#8]
Vcpkg is a tool to acquire and build C++ open source libraries on Windows:
https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/

Provide a vcpkg port for DXUT would be very convenience.

**Comment by walbourn** [comment]
I'm certainly considering vcpkg for DirectX Tool Kit, DirectXTex, DirectXMesh, and UVAtlas.

DXUT, however, is an application 'framework' rather than a true 'static library' in any real sense, as well as being a legacy solution. A Visual Studio project template would be more relevant for DXUT, but in general I would strongly encourage new projects to avoid using DXUT entirely. If you are looking for an 'easy to start new Direct3D projects' approach, use the [Direct3D VS Game Templates](https://blogs.msdn.microsoft.com/chuckw/2015/12/17/direct3d-game-visual-studio-templates-redux/) along with [DirectX Tool Kit](https://github.com/Microsoft/DirectXTK/wiki/Getting-Started) instead.
